# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: PowerShell@2
  displayName: 'Install Pester'
  inputs:
    targetType: 'inline'
    script: 'Install-Module -Name Pester -SkipPublisherCheck -Force -Verbose -Scope CurrentUser'

- task: PowerShell@2
  displayName: 'Install PSScriptAnalyzer'
  inputs:
    targetType: 'inline'
    script: 'Install-Module -Name PSScriptAnalyzer -SkipPublisherCheck -Force -Verbose -Scope CurrentUser'


- task: PowerShell@2
  displayName: 'Run PSScriptAnalyzer'
  inputs:
    targetType: 'inline'
    script: 'Invoke-ScriptAnalyzer -Path .\'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
